### ISSUE TITLE
Simple interactive evolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#1]
This repo is forked off of the basic interactive evolution example with just two options to choose from via the keyboard (run `train.py` to see this in action). In that code, you press either 1 or 2 at the keyboard to pick the one shape that you prefer, which evolves further.

The `evolve_CPPN.py` file I've made creates 10 CPPN-generated shapes and pauses for input, but does not do anything with the input yet. Add a way to do simple interactive evolution via the keyboard. Specifically, the user can enter something like:
`0 3 5` 
to indicate that out of the 10 options available (0 through 9), the ones at indexes 0, 3, and 5 should be used to generate offspring. Try implementing this basic input scheme and see what you can evolve (past some images in the issue thread to show off the results).

**Comment by MuellMark** [comment]
![Screenshot 3](https://user-images.githubusercontent.com/92736704/168914613-6024ad85-74ca-4dd4-84e3-08bcccd0080b.png)
![Screenshot 4](https://user-images.githubusercontent.com/92736704/168914619-d1b77a03-fde5-4cea-88ba-1cc35ba97378.png)
![Screenshot 5](https://user-images.githubusercontent.com/92736704/168914662-b710d15a-91e2-4074-906d-1f54f946fef0.png)
![Screenshot 6](https://user-images.githubusercontent.com/92736704/168914667-d1645456-9f03-4bf4-80fa-b2db4eb029a2.png)
![Screenshot 7](https://user-images.githubusercontent.com/92736704/168914668-a9dbcd28-c372-4405-acc3-ecb4e62513a3.png)

These are all from selecting red stone cubes to further generate red stone cubes (ideally) with each generation, they get more uniform in terms of structure

**Comment by MuellMark** [comment]
The code now asks the user which of the ten generate structures they like the most, then, their answer gets converted into a list of numbers. From there, the list _selected_ is filled with values of false if the numbers weren't selected, and true for any numbers that were. This is then fed into a for loop that sets the genome's fitness scores.
