### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#10]
The code is getting fairly complex. There are already several settings that it would be nice to experiment with. So, we need to have a separate Python file for handling the command line parameters. Once this exists, it will be the primary file that we execute, and from there the CPPN evolution will be launched.

Call the new file `main.py` and model it after `train.py` (we'll probably eventually delete most of the original files from the repo like this one). `train.py` provides a good example of parsing command line parameters that each have their own default values. After handling the command line parameters, `main.py` should call the `run` function in `evolve_CPPN.py`, but you will need to modify that function to take the `args` object as a parameter.

As for what parameters we should support (initially), they are all of the global constants written in ALL CAPS at the top of `evolve_CPPN.py`, namely `USE_ELITISM`, `IN_GAME_CONTROL`, `PRESENCE_THRESHOLD`, and `POPULATION_SIZE`. More will likely be added very soon.

**Comment by alejmedinajr** [comment]
Created command line parameters and put them in `main.py.`  It is also worth to note that now running `evolve_CPPN.py` will print **"Do not launch this file directly. Launch main.py instead."** because now main.py is the file that needs to be run.
