### ISSUE TITLE
Make xrange, yrange, and zrange be command line parameters

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#12]
Once #10 is completed, make the three parameters sent to `MinecraftBreeder` be command line parameters for easy modification of the size of the shapes. Try lots of different configurations and make sure that all the code that should generalize to different sizes actually works.

**Comment by schrum2** [comment]
After gathering the parameter values, do value and range checks to make sure appropriate values have been used, and crash with error messages otherwise. The shape sizes should not be too small, the evolution pop size should be at least 2, and other mostly common sense things.

**Comment by alejmedinajr** [comment]
Now xrange, yrange, zrange values too small will generate error message, and values too large will just print a warning statement. Also the pop size being less than 2 results in a error message as well.
