### ISSUE TITLE
Dynamic Presence Threshold Option

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#14]
Currently the PRESENCE_THRESHOLD determines whether or not a space is empty of occupied by a block of some kind.  

However, make a new command line parameter called DISTANCE_PRESENCE_THRESHOLD that is either true or false. If this is True, then the regular threshold is replaced by one that depends on the distance of the candidate block from the center of the generated shape. Define another command line parameter called DISTANCE_PRESENCE_MULTIPLIER with a default value of 0.01.

The effective presence threshold will then be DISTANCE_PRESENCE_MULTIPLIER * distance from center

**Comment by alejmedinajr** [comment]
Both of these command line parameters were added and seem to work when testing with the same random seed and increasing/decreasing `DISTANCE_PRESENCE_MULTIPLIER` while `DISTANCE_PRESENCE_THRESHOLD` was set to true.
