### ISSUE TITLE
More command line parameters

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#15]
Make BLOCK_LIST_EVOLVES and BLOCK_LIST_SIZE (defined at top of evolve_CPPN.py) into command line parameters

**Comment by alejmedinajr** [comment]
Added BLOCK_LIST_EVOLVES and BLOCK_LIST_SIZE command line parameters. Also added exception for when BLOCK_LIST_EVOLVES < 2.
