### ISSUE TITLE
CPPN encodes orientation of each block as well

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#17]
Currently, we are just orienting each placed block in the same way, and for most blocks that is fine. However, for some (especially pistons) the orientation matters. See how different orientations are implemented in the original interactive evolution project (code moved to the directory `originalinteractive`) and see if we can do something similar. This will definitely require our CPPNs to have additional output neurons.

**Comment by schrum2** [comment]
Actually, I think the way to do this is straight forward. Have a command line parameter EVOLVE_ORIENTATION that added 6 outputs to the CPPN (one for each direction), and whichever of those outputs is maximal determines the orientation of whatever block is currently being placed.

**Comment by schrum2** [comment]
I think it's safe to start this now. You'll need a command line parameter, you'll need to correctly set `config.genome_config.num_outputs` in `evolution.py` to the right number, and the rest will happen in the `generate_block` function of `cppn_generation.py`. @richeyme has already done something similar in this function for the Snake issue #23 by adding 7 additional CPPN outputs, 6 of which are used to pick what direction to move in next. You will only need 6 additional CPPN outputs, and will decide how to orient the block rather than which way to move.

However, I think you also have to consider the case where the orientation is evolved AND a snake is being evolved. This means the total number of CPPN outputs is 1 + num block types + 6 + 1 + 6. The 6s are from the `NUM_DIRECTIONS` (one for orientation and one for movement), the first 1 is for the presence output, and the second 1 is the the continuation output used in the Snake problem.

**Comment by MuellMark** [comment]
![2022-05-24_15 24 21](https://user-images.githubusercontent.com/92736704/170125666-23c95650-b1de-4ad4-8ec5-316130432600.png)
![2022-05-24_15 24 39](https://user-images.githubusercontent.com/92736704/170125680-3aa2ca23-27c4-4368-a534-f0793e975742.png)

These two images showcase that snakes can now be regenerated with different kinds of blocks, with evolved orientations

**Comment by MuellMark** [comment]
It is now possible to evolve orientations with blocks. First it was added to normal shapes, then to snakes. With evolving blocks enables, you can change the block types but keep the original orientation. Also, The ability to evolve the blocks for snakes was also added here, as it was a quick fi and we found out about it during implementing this
![2022-05-24_14 43 12](https://user-images.githubusercontent.com/92736704/170127681-b748b39d-c83c-4ad9-93bd-2af7c2f5f58c.png)
