### ISSUE TITLE
A fence around each evolved shape

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#2]
There are lots of little nice touches that could be added to make it more clear what is happening in the environment. For example, a little wooden fence could be placed around the border of each shape to clearly indicate where one ends and the next begins. This would be particularly useful for the totally empty space when the CPPN doesn't generate anything. This should be an easy task, but good for building up familiarity with working in Minecraft.

Whatever code generates the fences should be in a separate function (it can take the list of shape placement regions as a parameter). For the kind of shapes we are generating now, it makes sense to call this exactly once and never again. However, I can imagine us evolving structures that destroy their surrounding area (with lava or from pistons), so we might need to put the fences back every time. Just try to write the code in a way that is flexible and reusable.

**Comment by schrum2** [comment]
The pop_size tells you how many evolved structures there are, and therefore how many fence structures to make.
```
First, make one wall of a 4-sided fence.

Then loop pop_size number of times, going through each evolved structure
           Inside of this loop, you make the other three walls for one evolved structure at a time.
           Only three are needed because each structure shared a wall with at least one neighbor
```
Of course, making any given wall requires its own loop, since you have to loop the length of that wall and add a block on each iteration.

**Comment by richeyme** [comment]
I have added a method that spawns in fences around each of the structures
