### ISSUE TITLE
Have the "Next Generation" mechanism next to each switch

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#20]
It's a bit tedious to have to run back to the emerald switch to advance to the next generation. Instead, some sort of "next generation" button or switch should be next to every control panel in front of each shape. There does not need to be any kind of visual indicator of this (no redstone lamp), but you probably still need to somehow activate a (now completely hidden) piston, since this seems to be the easiest way to detect changes in the world state. If any of these new buttons/switches are activated, then the simulation advances to the next generation.

**Comment by richeyme** [comment]
I have spawned in the buttons and pistons that generated new structures when pressed.
