### ISSUE TITLE
Space between evolved shapes

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#22]
Putting the evolved shapes directly adjacent (with just a single fence separating them) means that some shapes interact with or even destroy each other (mainly lava). I think we need to put some space between adjacent shapes, which also means adding an additional fence line (since each shape needs to be fully enclosed in a fence).

The exact amount of spacing between shapes should default to 1, but be controlled by a new command line parameter SPACE_BETWEEN. Note that a value of 1 means there is a gap of one block between the fences, which means a gap of 3 blocks between the actual shapes.

**Comment by alejmedinajr** [comment]
There is now a functional command line parameter that spaces out the shapes. I also changed the fence method to where calling it builds the four "walls" around the shape.

![image](https://user-images.githubusercontent.com/100097809/169602365-98695b83-63b7-4325-956b-bbf72ba04abc.png)

**Comment by schrum2** [comment]
I broke this when merging, so it has to be fixed again. More details in upcoming commit message

**Comment by schrum2** [comment]
This can be closed again
