### ISSUE TITLE
Separate module for CPPN generation

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#25]
The method `query_cppn_for_shape` should be made into a function in a new module called `cppn_generation.py`. This is also where the code associated with the new issue #23 should go (specifically, the code that generates using the snaking style). Separating this code out will make it easier to use in a variety of places, such as the new fitness functions that are being developed as part of issue #19 

As usual, transforming into a function means all references to `self` instead have to be passed parameters

**Comment by schrum2** [comment]
Do this issue before working on #23. This new module will be where all approaches for using a CPPN to generate blocks will be stored. When you move the `query_cppn_for_shape` method here and change it to a function, also rename it to `query_cppn_for_volume_shape`.

Then, when you work on the snake approach for #23, you can make that function be `query_cppn_for_snake_shape`

**Comment by richeyme** [comment]
I have moved the method into the new module and it works as it should with the parameter changes
