### ISSUE TITLE
One parameter for x/y/z start and range

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#26]
We are ending up with a lot of functions that require `self.startx`, `self.starty`, `self.startz`, `self.xrange`, `self.yrange`, and `self.zrange` to all be passed as parameters. If you need one of these, you typically need all of them, so we should simplify this.

Instead of having these separate instance variables in the `MinecraftBreeder` class, have a single `self.position_information` instance variable that is a `dict` (dictionary). Set `self.position_information["xrange"]`, `self.position_information["startx"]`, etc to have the values, and then simply pass `self.position_information` as a parameter to all of those functions instead.

**Comment by richeyme** [comment]
I have changed the parameters for all the methods (at least that can be changed) and they all work properly

**Comment by richeyme** [comment]
Now I actually changed every single one
