### ISSUE TITLE
Make number placement depend on lower corner of generated shape

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#28]
After @richeyme completes #26 , modify `minecraft_structures.place_number` to take x/y/z coordinates of the lower corner of the shape they are generated on top of. Also, add the yrange as a parameter so you know how high to make the number.

In order to get access to the corner information, you'll need to move the calls to `place_number` into the `eval_fitness` method, so they will redraw every time.

The idea is to move as much complicated math as possible inside of the functions themselves so that any function associated with placing something relative to a generated shape can just use the corner location as a parameter to base the placement of everything else off of.

**Comment by richeyme** [comment]
After moving the method call and then using corner as part of the parameter, all the numbers spawn in fine except for the number 9, which looks like it first spawns an 8 underneath it before it gets replaced by air blocks. It looks like this:
![2022-05-20_16 20 37](https://user-images.githubusercontent.com/94399708/169612293-00a1fdf1-071d-4d1b-8f6f-944c4fac9455.png)

**Comment by schrum2** [comment]
Fixed this
