### ISSUE TITLE
Command line parameter to keep world on exit

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#32]
The default is now to clear and reset the world (clear space, restore ground) whenever the program exits (even if it crashes). However, we should allow a command line parameter that disables this. Be sure to look carefully at how bool type command line parameters work now.

**Comment by alejmedinajr** [comment]
I created the new command line parameter and it keeps the world on exit when set to default value of false. When it is changed to true, The previous shapes remain on exit.
