### ISSUE TITLE
DESIRED_BLOCK for type_count

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#37]
Make a parameter DESIRED_BLOCK that is any block name. This will have a type string, but inside of `main.py` after the value has been read in, you can convert args to be the integer that corresponds to the name. I think this would be done with BlockType somehow, but I'm not fully sure.

In any case, change the function header for `type_count` to replace `block_type` with `args` and get the `args.DESIRED_BLOCK` from the `args`

**Comment by schrum2** [comment]
I think this is resolved. Comment, test, and close if appropriate.

**Comment by schrum2** [comment]
Actually, this isn't done yet. The command line parameter works, but you still need to remove `block_type` from the parameter list for `type_count` and replace it with `args`

**Comment by alejmedinajr** [comment]
Removed `block_type `from the parameter list for `type_count `and replaced it with `args`.
