### ISSUE TITLE
Control evolution from inside of Minecraft

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#4]
The approach proposed by #1 should work, but going back and forth between Minecraft and the external console is not fun. It would be way better to select objects to evolve from inside the game directly.

I'm not sure what the full range of possibilities of the EvoCraft API are. I know that Minecraft support switches, buttons, pressure plates, etc, and any of these could be used as a means of selecting objects to evolve in the game. However, I don't know if the EvoCraft API is capable of detecting the various possible states of these redstone components, which would be required for the evolution code to know which shapes were selected.

However, I'm fairly certain that the EvoCraft API can detect when a piston is extended (the extended portion is its own block type that can be read from the world), so here is my idea. Put a face-up piston in front of each object. Set up some kind of switch or other mechanism that supplies power to the piston and extends it. If the piston in front of a shape is extended, then it is considered as selected. If the piston is down, then the shape is not selected.

In addition to this, you will also have to have some sort of mechanism (could also be a piston) that the user activates to indicate that the selection process is done, and the code can move on to generating shapes for the next generation.

**Comment by richeyme** [comment]
This is my idea for what the lever mechanism should look like:
![2022-05-18_13 30 00](https://user-images.githubusercontent.com/94399708/169119040-e4e61356-3f48-47db-9f84-0ba7c2a78cea.png)
![2022-05-18_13 30 09](https://user-images.githubusercontent.com/94399708/169119083-829f3fca-72aa-4a5b-b332-897a8b64b7d8.png)
![2022-05-18_13 31 57](https://user-images.githubusercontent.com/94399708/169119125-e15abed9-bece-4849-9548-dbad8f835ff8.png)

**Comment by richeyme** [comment]
This is another model with a redstone lamp that turns on and off instead of a glow stone that pops up:
![2022-05-18_13 50 08](https://user-images.githubusercontent.com/94399708/169128242-b2fcb3fb-9759-4cf3-8cc1-b36a51d977e5.png)

![2022-05-18_13 51 22](https://user-images.githubusercontent.com/94399708/169127985-673a0f3e-94c1-445e-8279-4c37cae15439.png)

![2022-05-18_13 53 23](https://user-images.githubusercontent.com/94399708/169129176-0c21f021-4b1e-48e7-8999-7b876a032286.png)

**Comment by richeyme** [comment]
This is what I have so far for each of the structures
![2022-05-18_16 23 45](https://user-images.githubusercontent.com/94399708/169162815-49b185b4-d93f-43f7-9322-e4d42b8aa1da.png)

**Comment by schrum2** [comment]
All we need now is the switch that advances to the next generation. However, as Mark found out #13 , some block combinations destroy a lot of the ground. We will need to add some checks that reconstruct the control switches if they are ever destroyed ... eventually.

**Comment by richeyme** [comment]
This is what the switches (both the selection and next gen) look like:
![2022-05-19_15 16 57](https://user-images.githubusercontent.com/94399708/169397224-94b827f2-1ce7-4bc2-8a75-7ac7554d0aae.png)
