### ISSUE TITLE
Identify final champion

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#44]
When using a fitness function, whenever a shape has a fitness value equal to or greater than the fitness threshold, add some blocks to the world that outline, surround, or otherwise single out the winning champion, so that the user will know to go look at that evolved shape.

**Comment by alejmedinajr** [comment]
Now `fitness_cppn_evolution `produces an arrow made of glow blocks when a shape meets the fitness threshold. 
![champion_of_fitness](https://user-images.githubusercontent.com/100097809/170126319-115046ea-05cc-4181-ae1c-0e1ac8a2a86a.png)

I am not sure if this is an issue, but if there are multiple shapes that meet the fitness function in one population, they both end up having arrows pointing down on them. 

![When_two_champions_in_one_population](https://user-images.githubusercontent.com/100097809/170126491-ea99c951-f0f9-4ac5-887c-a5dd25a57dd1.png)

**Comment by schrum2** [comment]
You need to make sure that any place where a down arrow could be is cleared at the start of fitness based evolution so that the arrows don't accumulate in the world.

**Comment by alejmedinajr** [comment]
The issue where the previous arrows were still being kept in the world has been resolved. Now the previous arrows are cleared at the start of fitness based evolution.
