### ISSUE TITLE
Unit tests for fitness_functions.py

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#47]
It turns out pytest is pretty easy to use. After installing it with from the requirements file, look at `test_util.py` and see how it works. Just run `pytest` in the project directory to execute the tests.

You will need to make a new file `test_fitness_functions.py` that contains functions `test_type_count` and `test_type_target`. Each will need to initialize a Minecraft server client connection (as done in the constructors for the two breeder classes), and use that to artificially create some shapes, before then using the fitness functions to retrieve the calculated scores.

Running these tests will only work if a Minecraft server is running on the local machine. That could be an issue eventually, but for now don't worry about it. Do keep in mind that this will put shapes into your Minecraft world. You make want to make sure that you empty the space before and after. You might also want to place the shapes somewhere else in the world than around (0,5,0), which is where most of our shapes evolve.

**Comment by alejmedinajr** [comment]
There are now 4 shapes that were created to test `type_count `fitness function. All 4 pass (the code is a little bit ugly however)
![unit test shapes](https://user-images.githubusercontent.com/100097809/170791772-605d3acd-b6e0-47e9-ab7d-b51bb19ddf1e.png)
.

**Comment by alejmedinajr** [comment]
Made unit tests for `type_target `using the same shapes (but around 100 spaces away in the z coordinate). I still need to display a better message when the tests are run while the server is not connected.

**Comment by alejmedinajr** [comment]
Both of the tests are now in try/except blocks in the case that the server is not connected.

New [more clear] error message produced when running the tests without successfully being connected to the server:

![error message](https://user-images.githubusercontent.com/100097809/171277437-8455be32-3917-4140-9734-a8115e0db9fc.png)
.
