### ISSUE TITLE
Clear all snake blocks after each generation

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#48]
`interactive_cppn_evolution.py` now maintains a `all_blocks` list that is used to clear out all the blocks generated by evolution after each generation. This is especially important when evolving snakes that go beyond the bounds of what is normally cleared.

Add similar functionality to `fitness_cppn_evolution.py`

**Comment by richeyme** [comment]
The sneks now get cleared after every generation
