### ISSUE TITLE
Save during interactive evolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#49]
Once #33 is done, add support to save during interactive evolution. If "s" is pressed then the current population will be saved.

**Comment by schrum2** [comment]
You won't really know whether it works until you have a way of loading what was saved, so wait until https://github.com/schrum2/EvoCraft-SCOPE/issues/57 is resolved to close this.

**Comment by MuellMark** [comment]
Now whenever "s" is pressed (both with and without in game controls), the shapes that were generated will now be saved in file specified by their see and generation it was on. This was tested with #57 to ensure that the correct shapes are not only saved, but also reloaded.
