### ISSUE TITLE
Reset or exit without in-game control

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#50]
If playing with console-based input, the user should still be able to reset or gracefully exit. At the prompt that asks users to provide their selections, if they instead enter "r" or "q" then the reset/quit actions should be carried out instead. If reset is executed, then the prompt to get user selections should repeat before advancing to the next generation

**Comment by MuellMark** [comment]
Also make sure to add a saving feature as well, similar to #49. Have it say "hit s to save" or something like that

**Comment by schrum2** [comment]
When using the the console to select, pressing r to reset adds the in-game control switches. This should not happen.

**Comment by MuellMark** [comment]
I believe saving the file now works and it is added as an option for the user controlled part, along with resetting and quitting. I also fixed generating switches here, as this is all console based

**Comment by schrum2** [comment]
You won't really know whether it works until you have a way of loading what was saved, so wait until #57 is resolved to close this.

**Comment by schrum2** [comment]
Actually, #49 is the issue for checking is saving works, so this one can close, and that one will remain open
