### ISSUE TITLE
Make several batch files for typical use cases

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#51]
The number of command line parameters we have is becoming a bit overwhelming. Let's add several batch files that execute the `main.py` script in combination with some commonly used command line parameter sets. However, the batch file itself should accept a numeric command line parameter itself that specifies the random seed (see how MM-NEAT batch files handle this).

Here are some batch files worth making (ask if the intended command line parameters are unclear):
`InteractiveConsoleCubes.bat`
`InteractiveInGameCubes.bat`
`InteractiveInGameSnakes.bat`
`FitnessMaxQuartzCubes.bat`
`FitnessTargetQuartzCubes.bat`
`FitnessFillSpaceSnakes.bat`

**Comment by alejmedinajr** [comment]
So far the following batch files have been made:
`FitnessMaxQuartzCubes.bat`
`FitnessTargetQuartzCubes.bat`
`FitnessFillSpaceSnakes.bat`

I also ended up moving them into their own folder called batch.

**Comment by schrum2** [comment]
Some changes. Set USE_ELITISM=True in main.py. We always want it to be true at this point, but we don't want to have to specify it in all of these batch files.

Change the numbering of the command line parameters to the match files so that the parameters will always be given in the order: BASE_DIR, EXPERIMENT_PREFIX, RANDOM_SEED, POPULATION_SIZE. Additional parameters unique to a particular batch file can come after these.

Make all fitness-based approaches use the machine block set.

**Comment by alejmedinajr** [comment]
Made the changes to the existing batch files. Will likely make the other batch files later today or next week.

**Comment by alejmedinajr** [comment]
Created the remaining batch files.
