### ISSUE TITLE
Variable block types

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#6]
Minecraft has so many block types that it makes sense to allow different CPPN genotypes to focus on different subsets of blocks. One way to so this is to combine each evolving CPPN genotype with an evolved list of block types. For now, we'll start simple and have the list be of a pre-determined fixed length for all genomes (which will allow us to fix the output dimension of the CPPNs). However, the list of specific blocks used by each initial genome will be completely randomized from the collection of all possible block types.

Unfortunately, doing this requires getting under the hood a bit with how NEAT-Python works, which has documentation online. Specifically, there is a section on this page about defining "New genome types": https://neat-python.readthedocs.io/en/latest/customization.html

It's probably a good idea to start separating the code out into separate files, so the new genome class used here should be in a new file that is imported into evolve_CPPN.py. The new genome will need to subclass the DefaultGenome, which would start like this:

`class CustomBlocksGenome(neat.DefaultGenome):`

I think a new `self.block_list` would need to be defined in the constructor and randomly initialized in `def configure_new(self, config):`

Mutation would randomly replace one of the block types with some small probability, and crossover would randomly pick between the lists from the two genomes (multi-point crossover).

You would sort of be following the example of the LanderGenome here:
https://github.com/CodeReclaimers/neat-python/blob/master/examples/openai-lander/evolve.py
Except, that class adds an extra numeric discount variable to the genome, whereas we would be adding a list of blocks.

**Comment by MuellMark** [comment]
We found out we can use list(mc.BlockType.keys()) to make a list of all values of blocks, list(mc.BlockType.keys()) to make a list of all names of blocks, and list(mc.BlockType.items()) to make a list of both in a tuple. These should help resolve issues in the new genome class.

**Comment by MuellMark** [comment]
![Screenshot 2](https://user-images.githubusercontent.com/92736704/169352520-27a25579-20e4-4e45-a2de-2cb789521fc4.png)
![2022-05-19_11 36 07](https://user-images.githubusercontent.com/92736704/169352523-fc3a3bca-9bde-4da1-82b1-0266b5e6da8a.png)
Awesome new generations!!!

**Comment by MuellMark** [comment]
![2022-05-19_11 39 09](https://user-images.githubusercontent.com/92736704/169352984-e9906d3f-60f3-4039-9958-c90db41df1b5.png)

**Comment by MuellMark** [comment]
We added a new file that holds a new custom genome. This genome has a list that contains all the possible block types, which can be mutated and can generate structures using all of the different block types. in evolve_CPPN, the ability toggle whether or not the block list evolves was also added. All of this was also tested. 

![2022-05-19_11 42 19](https://user-images.githubusercontent.com/92736704/169386676-bfb4a692-9b09-42c7-83ee-7272240733ab.png)


As You can see, many crazy block types can now be generated!
