### ISSUE TITLE
Professional README.md file

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#60]
We're at a point where this repo needs a README.md file. This is just a text file, but the md indicates that you can use markdown language: https://www.markdownguide.org/cheat-sheet/ .  It's sort of like a simpler version of HTML. You can look at the raw text of the readme for the main EvoCraft repo to see how they do things there: https://github.com/real-itu/Evocraft-py

Basically, we need a readme that tells people how to use this code, and gives credit to the sources we used. It should have a link to the original EvoCraft repo, and also to NEAT-Python. It should tell them to pip install the requirements.txt, and explain the instructions in #59 for setting up the server directory (maybe we can even make a batch file that does this for them). Finally, it should recommend running
`python main.py --help` but then also point out and explain the batch files being created in association with issue #51

**Comment by alejmedinajr** [comment]
The README file is now at a good starting point.
