### ISSUE TITLE
Saving and loading novelty search archived shapes

### ISSUE THREAD

**Issue by MuellMark** [schrum2/EvoCraft-SCOPE#63]
While novelty search is working, there isn't a way of saving or loading any of the generated shapes. However, because of how novelty search is, we want to be able to save and load the shapes in the archive as they are generated. The best was to do this is to save each shape individually as they are added to the archive. This way, even when the program is terminated, we have the archive that was slowly built up. Loading the archives will have to reflect this change too.

**Comment by schrum2** [comment]
Make the save location be a subdirectory named "archive" that is inside of the directory defined by the BASE_DIR, EXPERIMENT_PREFIX, and the RANDOM_SEED.

**Comment by MuellMark** [comment]
The files are saved with pickle and are saved in directories based on BASE_DIR, EXPERIMENT_PREFIX, and the RANDOM_SEED. They are saved as "shape#" where # is the counter for how many shapes there are saved total. To load them, the directory is located and then all of the shape files in the directory "archive" are added into a list and then generated. There were some other small things that changed here, such as giving fitness functions its own parameter. On top of this, all generated shapes are cleared with all_blocks (similar to how it is done in fitness_functions). For loading, all blocks are added to one big list, which is returned, and then cleared with a user input. This takes care of rouge snakes that get generated but not cleared with our current clear function

Below are some images from the gallery of novel shapes
![2022-06-01_09 51 35](https://user-images.githubusercontent.com/92736704/171436347-a08aac66-9e87-46d1-af5b-552587ee8e8f.png)
![2022-06-01_09 51 21](https://user-images.githubusercontent.com/92736704/171436386-8adc603c-56f9-4859-80c3-9034c8f6d794.png)
![2022-06-01_09 50 39](https://user-images.githubusercontent.com/92736704/171436412-cb030260-cc74-417c-aed3-34fc5dc3ab02.png)
![2022-06-01_10 35 29](https://user-images.githubusercontent.com/92736704/171443468-67890ef1-06c8-46cc-a062-acc96b1a293f.png)
