### ISSUE TITLE
Command block to erase item drops

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#69]
I want you to do this in the Python code first, and if it goes well you can do it in the Java code too.

`EvoCraft-SCOPE\EvoCraft-py-Backup` contains a copy of the server that lives with the repository. Users are supposed to copy this directory over to `EvoCraft-SCOPE\EvoCraft-py` before using it. Try launching the server in `EvoCraft-SCOPE\EvoCraft-py-Backup`. You will have to set the eula to true again. None of the files that are created here should be committed to the repo. 

However, next you need to go into the game and add the command block that kills spawned blocks. I believe this will change something in the contents of the world directory, and this change will need to be committed, along with whatever other files you need to add that contain the script for the command(s) you are executing.

Note: can the command block be placed super far away and out of sight? Or maybe close, but underground? We often clear the space around where the shapes evolved, and I don't want the command block to be cleared out. I also don't want it to be distracting to potential users.

Once this is committed, we'll need to see if someone else can check out the repo, start their world based off of the "backup" and get the benefit of the command block already being present.

**Comment by schrum2** [comment]
I guess this is a duplicate of #45 but with more specific instructions. Once this issue is resolved, you can close both

**Comment by richeyme** [comment]
I think that this will be able to be used in other people's servers. The blocks showed up in a copy that was made of the world, so it is promising

**Comment by schrum2** [comment]
I loaded your world and although I could not find exactly where the underground command blocks were, it did seem like dropped items were disappearing as soon as they were made. @alejmedinajr and @MuellMark should update from master, then delete their EvoCraft-py directories so they can start fresh from the Backup and take advantage of the automatic clearing of dropped items
