### ISSUE TITLE
User controlled block types

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#7]
This can only be completed after #6 .

Once the variable block types are part of the genotype, we can also provide a way for the user to modify the block types in-game. Here is an idea:

Each structure that is rendered in the world can have a space at ground-level in front of it were the list of block types in its genome is indicated. The list of blocks can be physically represented in the world by rendering each block in the list side by side.

Then, we can provide a way of changing what those blocks are in the game.

I'm a bit less certain what the best way to do this is. One idea is to make the player break and replace blocks in the list that the player wants to have in the genome instead, but the problem with this idea is that it assumes the player has an inventory of all possible blocks and can easily place whatever he/she wants in the world.

But maybe this could be part of the game ... in order to get a block, you have to first evolve it in a structure. Randomness makes anything possible, but requires a bit of time and luck. The user has the option of breaking blocks off of the evolved structures (if we provide the player with an actual pickaxe), and then using that limited supply of blocks to specify new block options in existing genomes.

Any other ideas?

**Comment by schrum2** [comment]
I guess in Creative Mode, users would have access to all the blocks they could need, so maybe there isn't a problem.

**Comment by schrum2** [comment]
It occurs to me that we can't safely place certain types of blocks in a standalone way (lava would flow into its neighbors for example). So, whenever you get around to this, I think the blocks need to be placed in individual dug-out holes surrounded by stone so the lava won't destroy them

**Comment by MuellMark** [comment]
So far I have these mock ups:
![2022-05-19_14 58 16](https://user-images.githubusercontent.com/92736704/169394207-772509bc-0d5c-4de3-abee-5c4c739c7f7d.png)

The blocks currently generated will (ideally) go in each of the holes. From there users could change them. These changes could even happen instantly

**Comment by MuellMark** [comment]
I'm working on adding the blocks that make up the structure in front of each individual structure. From there, scanners will be put in place which will allow users to update the specific generated structures in real time. But before this occurs, I need to figure out the placement of each block

**Comment by schrum2** [comment]
Whenever this eventually works, it should depend on a command line parameter (not always be an option). Something like MANIPULATE_BLOCK_TYPES_IN_GAME

**Comment by MuellMark** [comment]
Currently, the blocks in front of the shapes can be changed to alter the genome. With elitism, we were able to regenerate the shapes with the specified block type changed. For next time, we'll need to delete the space and then regenerate the object from there. Maybe we could keep something with elitism in to regenerate the exact same shape?

**Comment by schrum2** [comment]
Be sure to add the requested command line parameters (see above) and generally clean up the code. In fact, I think the structures used to display the shapes still need a bit of clean-up too.

In fact, one thing we need to consider is different possible numbers of blocks used in the shapes, as well as different possible shape widths. Basically, all of the blocks may not fit in a single row, and the code will need to eventually account for this and make additional rows as needed. Just try to keep this in mind when writing code now, so that it will be easier to upgrade it later.

**Comment by schrum2** [comment]
Also, the block pedestals are definitely out of alignment with the generated shapes. Adjust their placement to depend on the list of self.corners that is sent to several of the placement methods now.

**Comment by schrum2** [comment]
Block types in genomes are changing unexpectedly. When elitism is used, those genomes should not be mutated ... I think? In any case, put print statements in various methods within the CustomBlocksGenome to track down which method is the cause of the changes.

Also, when a random block is swapped in, don't allow the AIR type to replace a physical block.

**Comment by MuellMark** [comment]
Added two new methods, one that places all of the blocks in a block_list in front of the shape, and then one that reads in those blocks. From there, we have a loop running that continuously checks these blocks, and if the user changes any of them, any instances of the old block in the shape are changed to that of the newly placed block. This can be toggled on and off with a command line parameter, however, IN_GAME_CONTROL needs to be true for this to work.
![2022-05-23_14 18 30](https://user-images.githubusercontent.com/92736704/169895483-117a96fb-1968-46d0-b7bd-29c83adc6d68.png)
