### ISSUE TITLE
README Updates

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#73]
@alejmedinajr did the original README but I think it would be good for either @MuellMark or @richeyme to get some experience making such README files, and I have requests for a few updates.

- Start with a brief summary of what the project is about in general, and also explain that it was made during the summer as part of undergraduate research for SCOPE at SU
- Mention the required Java version and how to install it (it is mentioned in https://github.com/real-itu/Evocraft-py)
- Clarify that the code only actually works with Python 3.7 or 3.8 (I just found out it doesn't work with 3.9 because of a dependence on an older version of a library called Pillow)
- Go ahead and provide full install instructions (as in https://github.com/real-itu/Evocraft-py) starting with the use of the `git clone` command
- For the remaining steps, I think we should create a batch file that does the work for the user. The batch file can pip-install the requirements.txt file, and also make the renamed copy of the EvoCraft-py-Backup directory.
- The part at the end should provide a description of each sub-directory in the batch directory to give users a general sense of what each option does.
- Mention all of our names at the end

**Comment by schrum2** [comment]
This is for @richeyme now

**Comment by schrum2** [comment]
Good progress. I've made some tweaks of my own. Here are some additional instructions.

- Link to the NEAT users page in the initial description: https://www.cs.ucf.edu/~kstanley/neat.html
- Link to the Novelty Search Users page in the initial description: http://eplex.cs.ucf.edu/noveltysearch/userspage/
- Mention and link to the SCOPE page: https://www.southwestern.edu/undergraduate-research/scope/
- Link to SU: https://www.southwestern.edu/
- Mention that the research was done under the supervision of Dr. Schrum and link here: https://people.southwestern.edu/~schrum2/
- The `batch` instructions were made before breaking up the batch files into multiple subdirectories, so the instructions need to be updated.
- Interactive instructions should explain how the switches and buttons work

**Comment by richeyme** [comment]
There may need to be more pictures or better descriptions of the batch instructions but I think I have hit every point
