### ISSUE TITLE
Clear more initial space around shapes

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#8]
If a shape consists of pistons and redstone blocks, it could push outside of the borders is was generated within. This means that whenever space gets cleared before generating new structures, a bit of extra space surrounding the shapes also needs to be cleared.

Note that when this interacts with fences (#2) and number labels (#3) we want to make sure that we are not erasing them, or that we put them back in place after erasing them.

We might even need to make a point of properly restoring the floor beneath the shapes, but that aspect of the issue can be handled last.

**Comment by schrum2** [comment]
In order to test this, change the list of shapes used for evolution (ask @MuellMark) to things that are likely to break outside the borders. Pistons mixed with redstone are one possibility. Water is probably another, and maybe even lava.

**Comment by alejmedinajr** [comment]
This commit clears out a big area based on the population size and where blocks could spread. This commit does not include the removal of excessive code that does the same thing as the clear_area method.

**Comment by alejmedinajr** [comment]
Removed redundant code that cleared the same area (uses many different small cubes) as the new `clear_area `method (uses one single large cube).
