### ISSUE TITLE
Error with elitism

### ISSUE THREAD

**Issue by schrum2** [schrum2/EvoCraft-SCOPE#9]
Something about the way I'm implementing elitism sometimes results in a population consisting of more than 10 shapes being generated. This is a problem.

In general, it is probably not a good idea to change the NEAT configuration parameters during execution, but I don't know how else to get the flexibility we want. The problem is that I don't fully understand the consequences of changing the elitism parameter during execution.

**Comment by schrum2** [comment]
The NEAT Python documentation is here:
https://neat-python.readthedocs.io/_/downloads/en/stable/pdf/

For the `reproduce` method it says

"Changed in version 0.92: Previously, the minimum and maximum relative fitnesses were determined (contrary to the comments in the code) including members of species being removed due
to stagnation; it is now determined using only the non-stagnant species. The minimum size of
species was (and is) the greater of the min_species_size and elitism configuration parameters;
previously, this was not taken into account for compute_spawn(); this made it more likely
to have a population size above the configured population size"

This confirms that there is an interaction between the elitism setting, the min species size, and the pop_size (which can indeed change). I'm not sure what to do with this yet. I never bothered using species in MM-NEAT and it mostly worked just fine, but they are a built-in part of standard NEAT. We can either try to disable them somehow or make things work despite the species.

**Comment by schrum2** [comment]
This may not be as bad as I think ... it seems to happen when MANY items are selected from the population. Before trying to fix the problem, see if you can recreate it. Make sure USE_ELITISM is true

**Comment by richeyme** [comment]
![2022-05-19_15 48 45](https://user-images.githubusercontent.com/94399708/169402092-4a888d00-08f8-4705-a87e-167d55d61a30.png)
This happened after I chose 7 of the structures. It also didn't let me choose the same amount the next generation because it gave me an index out of bound exception

**Comment by schrum2** [comment]
This might have been affected by how population size is sent via command line parameters. Double check that the error still occurs with the updated code.

**Comment by richeyme** [comment]
I think the specific issue with selecting too many structures not working as it should has been resolved. I was able to selected from 7 - 10 structures multiple times without having an issue. The issue of not choosing any seems to be the issue that remains, as the last time I tried to generate new structures without selecting any, it only let me do it 5 times in a row before crashing

**Comment by schrum2** [comment]
I'm reopening this because elitism isn't behaving the way it should. When I select items, I expect ALL of them to be present in the next generation, but this is not happening. I wonder if maybe the unseen images ARE in the next generation, but are not being shown since we are cutting off the number of individuals displayed. First we need to verify whether this is true (switch back to looping though the pop_size in the config to display extra shapes) and then decide what to do about it (a better understanding of NEAT species could help).

**Comment by schrum2** [comment]
I think this problem is actually caused by the issue of block types changing when they should not, which was recently mentioned in #7. Look at this issue more closely after @MuellMark fixes the problem with #7 and see if it is resolved.

**Comment by schrum2** [comment]
I actually don't think there is an issue here, now that problems with #7 have been fixed
